### ISSUE TITLE
Type support

### ISSUE THREAD

**Issue by Zenthae** [erhosen-libs/pydjantic#29]
Hello, from what I can see, types are implemented, so, would it be possible to add the py.typed file for pylance, mypy and other type checker to work with this lib ?

**Comment by erhosen** [comment]
For `BaseDBConfig`? Or what kind of types do you mean?

**Comment by erhosen** [comment]
It would be nice to have types (and auto-completions in IDE) for:

```python
from django.conf import settings

settings.                        # <- here
```

But I'm afraid it's not possible by Django design. 

@q0w @andrey-lepekhin do you have idea how to implement that?

**Comment by q0w** [comment]
You can typecheck settings.* by https://github.com/typeddjango/django-stubs special mypy plugin, but no auto-completion
