### ISSUE TITLE
Pydantic serializer warnings, such as "Expected `multi-host-url` but got `dict` - serialized value may not be as expected"

### ISSUE THREAD

**Issue by earshinov** [erhosen-libs/pydjantic#31]
Even when running tests:

```
tests/test_to_django.py::test_to_django_settings
  D:\NVIDIA\third-party\_python\pydjantic\.venv\Lib\site-packages\pydantic\main.py:308: UserWarning: Pydantic serializer warnings:
    Expected `multi-host-url` but got `dict` - serialized value may not be as expected
    return self.__pydantic_serializer__.to_python(

tests/test_db_config.py::test_dsn_and_exact_config
  D:\NVIDIA\third-party\_python\pydjantic\.venv\Lib\site-packages\pydantic\main.py:308: UserWarning: Pydantic serializer warnings:
    Expected `str` but got `dict` - serialized value may not be as expected
    return self.__pydantic_serializer__.to_python(
```

Seems to come from database configuration, e.g. (in `test_dsn_and_exact_config`):

```
class DatabaseConfig(BaseDBConfig):
    # declared as str, but actually deserialized as dict (Django database configuration)❓
    default: str = Field(default="postgres://user:password@hostname:5432/dbname")
    replica: PostgresDB = PostgresDB()
```

Applications still run, however:
- Users (like myself) might think that there is something wrong with their Django settings
- Application will fail to start under `-Werror` python interpreter flag

**Comment by earshinov** [comment]
@erhosen , sure

Tests above are run with
- Python 3.11.3
- Django 4.2.7 (as specified in `poetry.lock`)

I observe the same errors in my project, running
- Python 3.10.11
- Django 4.1.4

**Comment by worldworm** [comment]
Hi there 👋🏻 

This may be a pragmatic approach and may not fix the root cause, but it will get rid of the warnings: Just set the type of your DatabaseConfig to `str | dict` or `str | dict[str, Any]`
````python
class DatabaseSettings(BaseDBConfig):
    """https://docs.djangoproject.com/en/dev/ref/settings/#databases"""
    default: str | dict[str, Any] = Field(
        default=str(f"sqlite:///{BASE_DIR}/db.sqlite3"),
        validation_alias="DATABASE_URL",
        conn_max_age=0,
        ssl_require=False,
    )
    model_config = SettingsConfigDict(env_file=BASE_DIR / ".env")
````
(Tested with Python 3.10.12, Django 5.0.6, pydjantic 1.1.4)

I'm not sure if this might be confusing, but if you want I can do a quick pr to add this to the tests and demo.

**Comment by erhosen** [comment]
> I'm not sure if this might be confusing, but if you want I can do a quick pr to add this to the tests and demo.

Thanks @worldworm, it would be nice to get rid of the warning!
