### ISSUE TITLE
Non-default types cannot be safely serialized by default

### ISSUE THREAD

**Issue by pySilver** [erhosen-libs/pydjantic#34]
When settings contains types that are not covered with `to_django` it is passes as-is to underlying variables. So if settings contains any of these types (and much more, any custom):

* Url
* NameEmail
* Emailstr
* IPv4Address
* IPv6Address

it will lead to unexpected behaviour since Django code and apps knows nothing about these types. This can be easily solved by calling `settings.model_dump(mode="json")` instead of `settings.model_dump()` (which targets `mode="python"` by default), however I have no idea how to force lazy gettext strings to pass this call. Or if that's even possible. 

```
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'django.utils.functional.lazy.<locals>.__proxy__'>
```

**Comment by pySilver** [comment]
Nah. That's not a good idea to use mode="json" since we may want to use callable(s) in settings. So probably the only viable solution is to include all known types from pydantic_core and modify `to_django` so it can handle additional types conversions.

**Comment by erhosen** [comment]
>  So probably the only viable solution is to include all known types from pydantic_core and modify to_django so it can handle additional types conversions.

Do I understand correctly that you're suggesting adding custom handlers for non-standard Pydantic types (like `Url`, `NameEmail`, etc.), similar to how we handle `SecretStr` and `SecretBytes` here?

https://github.com/erhosen-libs/pydjantic/blob/0a981396572909b40b1e278b4020a7560c741c93/pydjantic/pydjantic.py#L55-L56

If that's the case, I have no objections. It seems like a logical development for the library, and I'd be grateful if you could create the appropriate patch to address your issue.

In turn, I’ll promptly review it and release a new version to PyPI!

**Comment by pySilver** [comment]
Yeah. Unfortunately I haven't found any better solution other than handling custom types manually within 'to_django' function. It's not nice but there is no better way to do it at the moment.
